/**
 * Third-party notice generation and bundled-package inventory.
 *
 * Shared by the build (THIRD_PARTY_NOTICES.md) and the packager (SBOM), so
 * both always describe the same set of distributed packages.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const LICENSE_FILES = /^(licen[cs]e|copying|notice)(\.(md|txt))?$/i;

/** name, version, license, homepage and license texts of one installed package. */
export function packageInfo(root, name) {
  const dir = join(root, 'node_modules', ...name.split('/'));
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const texts = readdirSync(dir)
    .filter((f) => LICENSE_FILES.test(f))
    .sort()
    .map((f) => ({ file: f, text: readFileSync(join(dir, f), 'utf8').replace(/\r\n/g, '\n').trim() }));
  const repo = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url;
  return {
    name,
    version: pkg.version,
    license: typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'NOASSERTION'),
    homepage: pkg.homepage ?? null,
    repository: repo ? repo.replace(/^git\+/, '').replace(/\.git$/, '') : null,
    texts,
  };
}

/** Packages recorded by the last build as bundled into dist/mycelink.mjs. */
export function bundledPackages(root) {
  const notices = readFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), 'utf8');
  return [...notices.matchAll(/^## ((?:@[^/\s]+\/)?[^@\s]+)@(\S+)$/gm)].map((m) => ({ name: m[1], version: m[2] }));
}

export function thirdPartyNotices(root, names) {
  const lines = [
    '# Third-party notices',
    '',
    'Mycelink is licensed under the Apache License 2.0 (see `LICENSE` and `NOTICE`).',
    '',
    'The runtime bundle `dist/mycelink.mjs` includes the following third-party',
    'packages, unmodified, under their own licenses. This file is generated by',
    '`npm run build` from exactly the packages esbuild placed in the bundle; do',
    'not edit it by hand. Mycelink claims no ownership of this code.',
    '',
    '| Package | Version | License |',
    '|---|---|---|',
  ];
  const infos = names.map((n) => packageInfo(root, n));
  for (const info of infos) lines.push(`| ${info.name} | ${info.version} | ${info.license} |`);
  lines.push('');
  for (const info of infos) {
    lines.push(`## ${info.name}@${info.version}`, '');
    lines.push(`- License: ${info.license}`);
    if (info.repository) lines.push(`- Source: ${info.repository}`);
    lines.push('');
    if (info.texts.length === 0) {
      lines.push('_No license file is shipped in the package; see the license field above._', '');
    }
    for (const t of info.texts) {
      lines.push(`### ${t.file}`, '', '```text', t.text, '```', '');
    }
  }
  return lines.join('\n');
}

export function hasNodeModules(root) {
  return existsSync(join(root, 'node_modules'));
}
