#!/usr/bin/env node
/**
 * Build the shipped runtime: one self-contained ESM bundle.
 *
 *   dist/mycelink.mjs        controller + runtime dependencies (ajv, yaml, ...)
 *   THIRD_PARTY_NOTICES.md   generated from exactly the packages in the bundle
 *
 * Both are committed, because a Claude Code marketplace install copies the
 * repository as-is and never runs npm install or a TypeScript build. CI
 * rebuilds them and fails if the committed copies differ.
 *
 * Deterministic: no timestamps, no absolute paths, no source maps.
 *
 * Usage: node scripts/build.mjs [--outfile <path>] [--notices <path>]
 */
import { build } from 'esbuild';
import { chmodSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { thirdPartyNotices } from './lib/notices.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i === -1 ? fallback : resolve(process.argv[i + 1]);
}

const outfile = arg('--outfile', join(root, 'dist', 'mycelink.mjs'));
const noticesFile = arg('--notices', join(root, 'THIRD_PARTY_NOTICES.md'));
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// dist/ holds the bundle and nothing else; clear stale files from older layouts.
if (outfile === join(root, 'dist', 'mycelink.mjs')) rmSync(join(root, 'dist'), { recursive: true, force: true });
mkdirSync(dirname(outfile), { recursive: true });

const result = await build({
  absWorkingDir: root,
  entryPoints: ['src/index.ts'],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22.12',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  charset: 'utf8',
  metafile: true,
  logLevel: 'warning',
  // ajv is CommonJS; give bundled CJS a real require for Node built-ins.
  banner: {
    js: [
      `// Mycelink ${pkg.version} runtime bundle. Generated by scripts/build.mjs; do not edit.`,
      '// SPDX-License-Identifier: Apache-2.0. Bundled third-party code: see THIRD_PARTY_NOTICES.md.',
      "import { createRequire as __mycelinkCreateRequire } from 'node:module';",
      'const require = __mycelinkCreateRequire(import.meta.url);',
    ].join('\n'),
  },
});

// Paths in the metafile are relative to absWorkingDir, so nothing machine-
// specific leaks into the notices.
const bundled = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const m = /node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(input.replace(/\\/g, '/'));
  if (m) bundled.add(m[1]);
}

// The bundle starts with a hashbang, so esbuild already writes it executable
// on Linux and macOS (subject to umask). Pin the mode explicitly: git tracks
// it as 100755 to match the release ZIP, and a rebuild must not flip it.
// No-op on Windows, which has no executable bit.
chmodSync(outfile, 0o755);

writeFileSync(noticesFile, thirdPartyNotices(root, [...bundled].sort()), 'utf8');

const bytes = readFileSync(outfile).byteLength;
process.stdout.write(`built ${outfile} (${bytes} bytes); ${bundled.size} bundled packages\n`);
