/**
 * Minimal but realistic portfolio-graph fixtures shared by schema and
 * scheduler tests. Mutate a deep clone, never the exported object.
 */
export function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export const VALID_REPOSITORIES = {
  schema_version: 1,
  repositories: [
    {
      name: 'core',
      path: '../fixture-core',
      base_branch: 'main',
      role: 'producer',
      commands: {
        build: ['node', 'build.mjs'],
        test: ['node', '--test'],
      },
    },
    {
      name: 'api',
      path: '../fixture-api',
      base_branch: 'main',
      role: 'service',
      commands: { build: ['node', 'build.mjs'], test: ['node', '--test'] },
    },
    {
      name: 'web',
      path: '../fixture-app',
      base_branch: 'main',
      role: 'client',
      commands: { build: ['node', 'build.mjs'], test: ['node', '--test'] },
    },
  ],
};

export const VALID_GRAPH = {
  schema_version: 1,
  feature_id: 'FEAT-101',
  title: 'Queue-backed state sync',
  prd: 'PRD.md',
  plan: 'PLAN.md',
  acceptance_criteria: [
    { id: 'AC-1', text: 'Core publishes an order-status event' },
    { id: 'AC-2', text: 'API consumes the event and exposes it' },
  ],
  resources: {
    'full-runtime': { capacity: 1 },
    'deploy-slot': { capacity: 1 },
    'browser-worker': { capacity: 2 },
  },
  repositories: ['core', 'api'],
  capabilities: [
    {
      id: 'CAP-CORE-PUBLISH',
      repository: 'core',
      title: 'Publish order-status events',
      acceptance_criteria: ['AC-1'],
    },
    {
      id: 'CAP-API-CONSUME',
      repository: 'api',
      title: 'Consume order-status events',
      acceptance_criteria: ['AC-2'],
    },
  ],
  nodes: [
    {
      id: 'FEAT-101.core.publish.red',
      level: 'executable-node',
      repository: 'core',
      capability: 'CAP-CORE-PUBLISH',
      node_type: 'red-test',
      depends_on: [],
      allowed_paths: ['tests/**'],
      forbidden_paths: [],
      contract_inputs: [],
      contract_outputs: [],
      required_resources: [],
      required_evidence: ['red'],
      verification_commands: [{ id: 'targeted', command: ['node', '--test', 'tests/publish.test.js'] }],
      worker: {
        model: 'sonnet',
        effort: 'high',
        max_turns: 30,
        max_wall_clock_minutes: 45,
        max_attempts: 2,
        nested_delegation: false,
      },
      invalidation_rules: [],
      acceptance_criteria: ['AC-1'],
    },
    {
      id: 'FEAT-101.core.publish.impl',
      level: 'executable-node',
      repository: 'core',
      capability: 'CAP-CORE-PUBLISH',
      node_type: 'implementation',
      depends_on: ['FEAT-101.core.publish.red'],
      allowed_paths: ['src/**'],
      forbidden_paths: [],
      contract_inputs: [],
      contract_outputs: ['contracts/order-status.schema.json'],
      required_resources: [],
      required_evidence: ['red', 'green', 'regression'],
      verification_commands: [{ id: 'targeted', command: ['node', '--test', 'tests/publish.test.js'] }],
      worker: {
        model: 'sonnet',
        effort: 'high',
        max_turns: 30,
        max_wall_clock_minutes: 45,
        max_attempts: 2,
        nested_delegation: false,
      },
      invalidation_rules: [],
      acceptance_criteria: ['AC-1'],
    },
    {
      id: 'FEAT-101.api.consume.impl',
      level: 'executable-node',
      repository: 'api',
      capability: 'CAP-API-CONSUME',
      node_type: 'implementation',
      depends_on: ['FEAT-101.core.publish.impl'],
      allowed_paths: ['src/**'],
      forbidden_paths: [],
      contract_inputs: ['contracts/order-status.schema.json'],
      contract_outputs: [],
      required_resources: [],
      required_evidence: ['red', 'green', 'regression'],
      verification_commands: [{ id: 'targeted', command: ['node', '--test', 'tests/consume.test.js'] }],
      worker: {
        model: 'sonnet',
        effort: 'high',
        max_turns: 30,
        max_wall_clock_minutes: 45,
        max_attempts: 2,
        nested_delegation: false,
      },
      invalidation_rules: [],
      acceptance_criteria: ['AC-2'],
    },
    {
      id: 'FEAT-101.e2e.acceptance.full',
      level: 'executable-node',
      repository: null,
      capability: null,
      node_type: 'e2e-scenario',
      depends_on: ['FEAT-101.api.consume.impl'],
      allowed_paths: [],
      forbidden_paths: [],
      contract_inputs: [],
      contract_outputs: [],
      required_resources: ['full-runtime', 'browser-worker'],
      required_evidence: ['e2e'],
      verification_commands: [{ id: 'e2e', command: ['node', 'e2e.mjs'] }],
      worker: {
        model: 'sonnet',
        effort: 'medium',
        max_turns: 10,
        max_wall_clock_minutes: 30,
        max_attempts: 1,
        nested_delegation: false,
      },
      invalidation_rules: [],
      acceptance_criteria: ['AC-1', 'AC-2'],
    },
  ],
};
